{% set name = "emd" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/emd-{{ version }}.tar.gz
  sha256: bd5e5fe6bf3bd11fb7d2429bd3671b74804d715d76f64e9d451e40125b5dd6b6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy >=1.19.3
    - scipy
    - matplotlib-base
    - pandas
    - pyyaml >=5.1
    - sparse
    - joblib
    - tabulate
    - dcor

test:
  imports:
    - emd
  commands:
    - pip check
    - python -c "import emd; assert emd.__version__ == '{{ version }}', emd.__version__"
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://pypi.org/project/emd/
  summary: Empirical Mode Decomposition
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  description: Empirical Mode Decomposition tools in Python
  dev_url: https://gitlab.com/emd-dev/emd
  doc_url: https://emd.readthedocs.io

extra:
  recipe-maintainers:
    - ajquinn
    - larsoner
