{% set name = "emd" %}
{% set version = "0.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emd-{{ version }}.tar.gz
  sha256: 38682f72adf7c406b7fc87316659fd159450b1dd946d48666deb893ef92c1fdc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy >=1.19.3
    - scipy
    - matplotlib-base
    - pandas
    - pyyaml >=5.1
    - sparse
    - joblib
    - tabulate
    - dcor

test:
  imports:
    - emd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/emd/
  summary: Empirical Mode Decomposition
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  description: Empirical Mode Decomposition tools in Python
  dev_url: https://gitlab.com/emd-dev/emd
  doc_url: https://emd.readthedocs.io

extra:
  recipe-maintainers:
    - ajquinn
    - larsoner
