{% set name = "emd" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emd-{{ version }}.tar.gz
  sha256: 97a518dfffb419d28fa9d8942c2ab23dd4cfccd0fce0c4d2cdb6df902aaa631c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy <1.21,>=1.17
    - scipy
    - matplotlib-base
    - pandas
    - pyyaml >=5.1
    - sparse
    - joblib

test:
  imports:
    - emd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/emd/
  summary: Empirical Mode Decomposition
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  description: Empirical Mode Decomposition tools in Python
  dev_url: https://gitlab.com/emd-dev/emd
  doc_url: https://emd.readthedocs.io

extra:
  recipe-maintainers:
    - ajquinn
