{% set name = "emd" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emd-{{ version }}.tar.gz
  sha256: a794bec95bcff5103f1c7b72d59dc955e7529817c713778ba9c9a36bd20b517f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy <1.22,>=1.17
    - scipy
    - matplotlib-base
    - pandas
    - pyyaml >=5.1
    - sparse
    - joblib
    - tabulate
    - dcor

test:
  imports:
    - emd
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/emd/
  summary: Empirical Mode Decomposition
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  description: Empirical Mode Decomposition tools in Python
  dev_url: https://gitlab.com/emd-dev/emd
  doc_url: https://emd.readthedocs.io

extra:
  recipe-maintainers:
    - ajquinn
